/* Generated By: 1.3 $ ($Date&JavaCC: Do not edit this line. ActorShellParserConstants.java */
package osl.service.shell;

public interface ActorShellParserConstants {

	int EOF = 0;
	int CLOSE = 5;
	int RECONNECT = 6;
	int INST = 7;
	int INVOKE = 8;
	int PRINT = 9;
	int MAKEGLOBAL = 10;
	int CREATEIMPL = 11;
	int CREATELOC = 12;
	int CREATE = 13;
	int SEND = 14;
	int MSGQUEUESIZE = 15;
	int MSGGETMETHOD = 16;
	int MSGGETARGS = 17;
	int MSGGETSENDER = 18;
	int MSGISRPC = 19;
	int MSGGETTAGS = 20;
	int DELMSG = 21;
	int SERVICE = 22;
	int TYPEIT = 23;
	int NEWLINE = 24;
	int TRUTH = 25;
	int FALSITY = 26;
	int NULL = 27;
	int DOT = 28;
	int INTEGER_LITERAL = 29;
	int DECIMAL_LITERAL = 30;
	int HEX_LITERAL = 31;
	int OCTAL_LITERAL = 32;
	int FLOATING_POINT_LITERAL = 33;
	int EXPONENT = 34;
	int CHARACTER_LITERAL = 35;
	int STRING_LITERAL = 36;
	int SHELL_VAR = 37;
	int GLOBAL_SHELL_VAR = 38;
	int SHELL_VAR_ARRAY = 39;
	int GLOBAL_SHELL_VAR_ARRAY = 40;
	int SELF_VAR = 41;
	int IDENTIFIER = 42;
	int LETTER = 43;
	int DIGIT = 44;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\r\"", "\"\\f\"",
			"\"close\"", "\"reconnect\"", "\"inst\"", "\"invoke\"",
			"\"print\"", "\"makeglobal\"", "\"createimpl\"", "\"createloc\"",
			"\"create\"", "\"send\"", "\"msgqueuesize\"", "\"msggetmethod\"",
			"\"msggetargs\"", "\"msggetsender\"", "\"msgisrpc\"",
			"\"msggettags\"", "\"delmsg\"", "\"service\"", "\"type\"",
			"\"\\n\"", "\"true\"", "\"false\"", "\"null\"", "\".\"",
			"<INTEGER_LITERAL>", "<DECIMAL_LITERAL>", "<HEX_LITERAL>",
			"<OCTAL_LITERAL>", "<FLOATING_POINT_LITERAL>", "<EXPONENT>",
			"<CHARACTER_LITERAL>", "<STRING_LITERAL>", "<SHELL_VAR>",
			"<GLOBAL_SHELL_VAR>", "<SHELL_VAR_ARRAY>",
			"<GLOBAL_SHELL_VAR_ARRAY>", "\"SV_self\"", "<IDENTIFIER>",
			"<LETTER>", "<DIGIT>", "\"<\"", "\">\"", "\":\"", };

}
